name: Trigger
# on: workflow_dispatch # workflow manual dispatch
on: 
  push:
    branches: 
        - 'feature*' # trigger on all feature branches. any branch starting with feature

jobs:
    trigger:
        runs-on: ubuntu-latest
        steps:
            # - name: Manual dispatch
            #   run: echo "manually dispatched"
            - name: feature branch push
              run: echo "feature branch push"